"""
Django settings for vahad_project project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import shutil
import urllib.parse
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = (os.environ.get('DJANGO_SECRET_KEY') or '').strip() or 'django-insecure-5c)f41c8s9#nz@ifj5kg-128iui5g4o6z+xgoqzfxo4yzzm*8c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (os.environ.get('DEBUG') or 'True').strip().lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://*.vercel.app',
    'https://*.now.sh',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# Authentication URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vahad_app',
    'crispy_forms',
    'crispy_bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vahad_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'vahad_app.context_processors.locations_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'vahad_project.wsgi.application'


# Database Configuration
# Supports DATABASE_URL (PostgreSQL/MySQL), remote DB_HOST, Vercel Serverless /tmp SQLite, and local MySQL/SQLite
def get_database_config():
    # 1. DATABASE_URL / POSTGRES_URL / MYSQL_URL
    database_url = os.environ.get('DATABASE_URL') or os.environ.get('POSTGRES_URL') or os.environ.get('MYSQL_URL')
    if database_url:
        url = urllib.parse.urlparse(database_url)
        engine = 'django.db.backends.sqlite3'
        if 'postgres' in url.scheme:
            engine = 'django.db.backends.postgresql'
        elif 'mysql' in url.scheme:
            engine = 'django.db.backends.mysql'
        
        return {
            'ENGINE': engine,
            'NAME': url.path[1:] if url.path else '',
            'USER': url.username or 'root',
            'PASSWORD': url.password or 'Hari@9361',
            'HOST': url.hostname or '',
            'PORT': str(url.port or ('5432' if 'postgres' in engine else '3306')),
        }

    # 2. Explicit DB_HOST (Cloud MySQL or configured remote database)
    db_host = (os.environ.get('DB_HOST') or os.environ.get('MYSQL_HOST') or '').strip()
    is_vercel = bool(os.environ.get('VERCEL') or os.environ.get('VERCEL_ENV') or os.environ.get('AWS_LAMBDA_FUNCTION_NAME') or os.environ.get('LAMBDA_TASK_ROOT'))
    
    # If DB_HOST is set to a remote server (ignore localhost on Vercel since Vercel cannot reach user's local PC)
    is_local_host = db_host in ('127.0.0.1', 'localhost', '0.0.0.0', '::1', '') or db_host.startswith('127.0.0.1:') or db_host.startswith('localhost:')
    if db_host and not (is_vercel and is_local_host):
        return {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('DB_NAME', os.environ.get('MYSQL_DATABASE', 'Vahadtms')),
            'USER': os.environ.get('DB_USER', os.environ.get('MYSQL_USER', 'root')),
            'PASSWORD': os.environ.get('DB_PASSWORD', os.environ.get('MYSQL_PASSWORD', 'Hari@9361')),
            'HOST': db_host,
            'PORT': os.environ.get('DB_PORT', os.environ.get('MYSQL_PORT', '3306')),
        }

    # 3. Vercel Serverless Lambda runtime
    if is_vercel:
        tmp_db = Path('/tmp/db.sqlite3')
        src_db = BASE_DIR / 'db.sqlite3'
        
        # Copy bundled database to writable /tmp directory if it doesn't exist yet
        if not tmp_db.exists() or tmp_db.stat().st_size == 0:
            if src_db.exists() and src_db.stat().st_size > 0:
                try:
                    shutil.copyfile(src_db, tmp_db)
                except Exception as e:
                    print(f"Warning copying SQLite database to /tmp: {e}")
        
        db_path = '/tmp/db.sqlite3' if os.path.exists('/tmp') else str(src_db)
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': db_path,
        }

    # 4. Local Development: Try MySQL, fallback to SQLite if MySQL service is offline
    try:
        import pymysql
        conn = pymysql.connect(
            host='127.0.0.1',
            user=os.environ.get('DB_USER', 'root'),
            password=os.environ.get('DB_PASSWORD', 'Hari@9361'),
            database=os.environ.get('DB_NAME', 'Vahadtms'),
            port=int(os.environ.get('DB_PORT', 3306)),
            connect_timeout=2
        )
        conn.close()
        return {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('DB_NAME', 'Vahadtms'),
            'USER': os.environ.get('DB_USER', 'root'),
            'PASSWORD': os.environ.get('DB_PASSWORD', 'Hari@9361'),
            'HOST': '127.0.0.1',
            'PORT': os.environ.get('DB_PORT', '3306'),
        }
    except Exception:
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(BASE_DIR / 'db.sqlite3'),
        }

DATABASES = {
    'default': get_database_config()
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

WHITENOISE_MANIFEST_STRICT = False

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
