# Generated by Django 5.1.5 on 2026-02-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vahad_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destination_images/'),
        ),
    ]
