# Generated by Django 6.0.6 on 2026-08-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vahad_app', '0002_alter_category_image_alter_destination_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='no-reply@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
