# Generated by Django 6.0.6 on 2026-08-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vahad_app', '0003_booking_address_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='booking',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='destination',
            table='destination',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
    ]
